stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/pro
  model:
    cmd: python src/model.py
    deps:
    - data/pro
    - src/model.py
    outs:
    - model.pkl
  model_evl:
    cmd: python src/model_evl.py
    deps:
    - model.pkl
    - src/model_evl.py
    metrics:
    - metrics.json
